name = "backend"
compatibility_date = "2024-09-27"
compatibility_flags = [ "nodejs_compat" ]

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiZTIyNmM5NzYtZDRiOC00OWE4LWE0YWMtM2NhODRiYjNkODkzIiwidGVuYW50X2lkIjoiOTU5M2YyYzRmMmQyNTIyNGQwYjU2NWJjYWEzMzJiNDg3NDFlOWMwYTUzZmExNGQ3Njg0ZmUxNjk2ODhkMmU2NyIsImludGVybmFsX3NlY3JldCI6ImNmMzg5ZmQyLWQ1MTYtNDA4Zi1iM2FhLTUwMzE4NzY3NWVhYiJ9.9TTscQN9uUDGte6E319mmK8yK1ha9B3-MwujAE6dIuQ"
JWT_SECRET="Hehehe"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"